version: '3.6'
services:
  ########################################################## neo4j
  neo4j:
    image: neo4j:4.4.9
    container_name: neo4j
    restart: always
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASS}
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data/neo4j:/data
