version: '3.6'
services:
  ########################################################## mookuauhau-backend
  api:
    image: hawaiiansintech/mookuauhau-backend
    container_name: api
    build:
      context: .
    env_file:
      - .env
    environment:
      HASURA_GRAPHQL_ENDPOINT: ${HASURA_GRAPHQL_ENDPOINT}
      NHOST_BACKEND_URL: ${NHOST_BACKEND_URL}
    volumes:
      - ./src:/app/src:cached

  ########################################################## hasura-cli
  hasura-cli:
    image: hasura/graphql-engine:v2.8.3.cli-migrations-v3
    container_name: hasura-cli
    entrypoint: /bin/hasura-cli
    environment:
      HASURA_GRAPHQL_ENDPOINT: ${HASURA_GRAPHQL_ENDPOINT}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
    volumes:
      - ./hasura:/hasura
    working_dir: /hasura
    profiles:
      - donotstart


  ########################################################## nhost
  mb-hasura-postgres:
    image: postgres
    container_name: mb-hasura-postgres
    restart: always
    volumes:
      - ./data/mb-hasura/db:/var/lib/postgresql/data
      - ./docker/mb-hasura/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: secretpgpassword
    ports:
      - '5413:5432'
  mb-hasura-graphql-engine:
    image: hasura/graphql-engine:v2.8.3
    container_name: mb-hasura-graphql-engine
    depends_on:
      - 'mb-hasura-postgres'
    restart: always
    ports:
      - '8089:8080'
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:secretpgpassword@mb-hasura-postgres:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
